### ISSUE TITLE
Error when accessing a Downloads Category

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#347]
When accessing a category in the downloads...

http://localhost/forum/index.php?action=tportal;dl=cat1

Results in:

Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OFFSET 0 LIMIT 10' at line 9

**Comment by tinoest** [comment]
Fixed in #348

**Comment by Bopske** [comment]
Actually not solved...

still happening.

Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OFFSET 0 LIMIT 10' at line 9
 http://localhost/forum/index.php?action=tportal;dl=cat1
 C:/xampp/htdocs/forum/Sources/TPdlmanager.php (Line 1010)

**Comment by Bopske** [comment]
Solved after all: I just missed the last update when I pulled recent changes. Fixed now!
